---
apiVersion: v1
kind: Service
metadata:
  name: stage-rs-ms-ob
  labels:
    app: stage-rs-ms-ob
spec:
  type: NodePort
  ports:
    - port: 80
      name: stage-rs-ms-ob-nginx
    - port: 9000
      name: stage-rs-ms-ob-php
  selector:
    app: stage-rs-ms-ob